server:
  port: 80
spring:
  cloud:
    stream:
      binders:
        iothub-builtin-endpoint:
          type: eventhub
          default-candidate: false
          environment:
            spring:
              cloud:
                azure:
                  eventhub:
                    connection-string: Endpoint=sb://iothub-ns-connex-iot-19283411-0f8b344974.servicebus.windows.net/;SharedAccessKeyName=iothubowner;SharedAccessKey=DB4sz9HR+gbO1hw0dmRD5A07MNIFySSaU90d1LcyNna=;EntityPath=connex-iothub
                    checkpoint-storage-account: connexstorage  #storage account name
                    checkpoint-access-key: raTYYaIv6zDD25Xn5J/mJ8jRETDGhKYXKGTjcLI0OyvLoVOvDipM8gLpadVjduexji4ygSVB1lvklcnzrCPahw==
                    checkpoint-container: connexiothubcheckpoints  #storage container name
        websocket:
          type: websocket
          default-candidate: false
          #  environment:
          #   spring:
          #    cloud:
          #      websocket:
          #        endpoint: /ws
      #Functions
      function:
        definition: receive;websocketTest;websocketMessages
      
      #Bindings
      bindings:
        receive-in-0:
          binder: iothub-builtin-endpoint
          destination: connex-iothub #iot/event hub name
          group: telemetry-debug  #use a different consumer group for debugging
        websocketTest-in-0:
          binder: websocket
          destination: websocket
        websocketMessages-out-0:
          binder: websocket
          destination: websocket

    websocket:
      endpoint: /ws

  integration:
    poller:
      fixed-delay: 2  #interval for the poller to call message producer

azure:
  iothub:
    connection-string: "HostName=connex-iothub.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=DB4sz9HR+gbO1hw0dmRD5A07MNIFySSaU90d1LcyNna="
    host-name: "connex-iothub.azure-devices.net"
    sas-key: "DB4sz9HR+gbO1hw0dmRD5A07MNIFySSaU90d1LcyNna="